### ISSUE TITLE
where can i find prediction.csv file?

### ISSUE THREAD

**Issue by yeongha-shin** [wayveai/LingoQA#5]
python ./benchmark/evaluate.py --predictions_path ./path_to_predictions/predictions.csv

in this command, where can i download or find predictions.csv file?

**Comment by aikedaerC** [comment]
> python ./benchmark/evaluate.py --predictions_path ./path_to_predictions/predictions.csv
> 
> in this command, where can i download or find predictions.csv file?



> python ./benchmark/evaluate.py --predictions_path ./path_to_predictions/predictions.csv
> 
> in this command, where can i download or find predictions.csv file?

Apparently, it should be generated by your testing VLMs. BTW, LingoJudge is one of the evaluation methods in this [challenge](https://cvpr24-advml.github.io).

**Comment by amm272** [comment]
This is correct, the `predictions.csv` file should be generated by the VLM that you would like to test.
