### ISSUE TITLE
Details about the single frame version.

### ISSUE THREAD

**Issue by exiawsh** [wayveai/LingoQA#6]
If I want to train a single frame lingo-QA model, how do I select keyframes in the video? (That is, the single frame model in the paper selects which image, the first or the last one in the video)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Mozhgan91** [comment]
This is also my question. what frames are used to achieve the results for the single-frame version?

**Comment by amm272** [comment]
The results for single-frame were achieved using the central frame of the video. Hope this helps!
